export { default as Box } from './Box'
export { default as Text } from './Text'
export { default as Home } from './Home'
export { default as Frenlancing } from './Frenlancing'
export { default as EngagementHiway } from './EngagementHiway'
export { default as Members } from './Members'
export { default as Teams } from './Teams'
export { default as Contact } from './Contact'
export { default as Video } from './Video'
export { default as Formation } from './Formation'
export { default as ModesGestion } from './ModesGestion'
export { default as Tools } from './Tools'
export { default as Partenaires } from './Partenaires'
export { Heading1, Heading2, Heading3 } from './Heading'
export { default as MissionHiway } from './MissionHiway'
export { Speetch } from './Speetch'
export { Parcours } from './Parcours'
