export { default as Box } from './Box'
export { default as Text } from './Text'
export { Home } from './Home'
export { Frenlancing } from './Frenlancing'
export { Members } from './Members'
export { Contact } from './Contact'
export { Video } from './Video'
export { Heading1, Heading2, Heading3 } from './Heading'
export { MissionHiway } from './MissionHiway'
export { Speetch } from './Speetch'
export { Parcours } from './Parcours'
export { Faas } from './Faas'
export { Hipay } from './Hipay'
